name: Release MAUI Windows App

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Ensure .NET 8 is installed

      # Step 3: Install MAUI workload
      - name: Install .NET MAUI workload
        run: dotnet workload install maui

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore MauiApp1/MauiApp1.sln

      # Step 5: Build the app
      - name: Build the app
        run: dotnet build MauiApp1/MauiApp1.sln -f net8.0-windows10.0.19041.0 -c Release

      # Step 6: Publish the app
      - name: Publish the app
        run: dotnet publish -f net8.0-windows10.0.19041.0 -c Release -o MauiApp1/output MauiApp1/MauiApp1.sln
        
      # Step 7: Install Squirrel globally
      - name: Install Squirrel
        run: npm install -g squirrel

      # Step 7.1: Add NPM Global to PATH
      - name: Add NPM Global Binaries to PATH
        run: echo "$(npm config get prefix)/node_modules/.bin" >> $GITHUB_PATH

      # Step 8: Package with Squirrel
      - name: Package with Squirrel
        run: |
          cd MauiApp1/output
          squirrel --releasify MyApp.exe --output-dir="../../squirrel-releases"
          
